### ISSUE TITLE
Color gap does not change shape on small user profile popout

### ISSUE THREAD

**Issue by SqueakyBeaver** [DiscordStyles/RadialStatus#19]
When you click a user's avatar, then the color gap does not change with the avatar shape. 
When I add the following to my live css code, the gap shape will change:
```css
#app-mount .wrapper-3t9DeA[style*="width: 80px;"].avatar-37jOim  {
   border-radius: var(--rs-avatar-shape);
}
```
Before css added:
![image](https://user-images.githubusercontent.com/63939550/122295734-3056c380-cebf-11eb-9264-3083836cdbc2.png)

After:
![image](https://user-images.githubusercontent.com/63939550/122295748-3482e100-cebf-11eb-8fad-705349cac61b.png)

 (Avatar shape is set to 0%)
