### ISSUE TITLE
status length issue

### ISSUE THREAD

**Issue by AcesGamingUK** [DiscordStyles/RadialStatus#40]
### Describe the bug
users with LONG statuses conflict with other themes  

### To Reproduce  
Have friends with long statuses and a theme that change the friend list layout 

### Screenshots
![image](https://user-images.githubusercontent.com/16180389/171773712-8fb8cdfa-5b1a-4e2d-ae6c-a9159fa33a71.png)

### Infomation (please complete the following information)
**Discord channel**: *Stable*  
**OS**: *Windows*  
**Mod**: *BetterDiscord*  
**Discord language**: *English*  

### Additional context
The theme I'm using is [DiscordNight](https://github.com/KillYoy/DiscordNight)

**Comment by AcesGamingUK** [comment]
i did some tweaking and i found adding the following into custom CSS helps
```css

.userInfo-2WpsYG,
.peopleListItem-u6dGxF {
  overflow: hidden;
  align-items: center;
  align-content: flex-start;
},
.peopleList-2VBrVI,
.textRuler-1DsANg, 
.text-MPIeXO {
    white-space: pre-line;
    text-overflow: clip;
    overflow: hidden;
    align-items: center;
    align-content: flex-start;
    font-size: 14px;
    line-height: 20px;
```
as you can see in the following screen
![image](https://user-images.githubusercontent.com/16180389/171780414-257387c9-f5a6-4f9c-83f0-74fe7e5c70a2.png)
