### ISSUE TITLE
Radial Status is missing from users image

### ISSUE THREAD

**Issue by Nerxxy** [DiscordStyles/RadialStatus#41]
### Describe the bug
Radial Status is missing from users image - see image

### Screenshots
![image](https://user-images.githubusercontent.com/37718547/171859588-f6b5c4bf-f904-4b90-86ee-64ae3c910c2e.png)

### Infomation (please complete the following information)
**Discord channel**: *Stable*  
**OS**: *Windows*  
**Mod**: *BetterDiscord*  
**Discord language**: *English*  

Unless I'm mistaken there used to be one there

**Comment by Gibbu** [comment]
No you're not mistaken. I removed it from that Avatar so it wouldn't conflict when talking in a voice chat.

**Comment by Nerxxy** [comment]
> No you're not mistaken. I removed it from that Avatar so it wouldn't conflict when talking in a voice chat.

Is there a way i can add it back? As i have hidden the circle that appears when in a voice chat, assuming we are talking about the same thing.

Are u talking about the ring that comes up in around the pfp in the image i sent?

**Comment by KewlSage** [comment]
this seeeeems to do it, could be more lines that should effect it but i can't tell the difference between having this and removing all `:not(.avatar-1EWyVD)`
```css
#app-mount .wrapper-1VLyxH svg:not(:root) {
  overflow: visible;
}
#app-mount .wrapper-1VLyxH rect {
  x: 0;
  y: 0;
  width: 100%;
  height: 100%;
  -webkit-mask: none;
          mask: none;
  display: block;
  rx: var(--rs-avatar-shape);
  ry: var(--rs-avatar-shape);
  fill: transparent !important;
  stroke-width: var(--rs-small-width);
}
#app-mount .wrapper-1VLyxH:not([style*="80px;"]):not([style*="120px;"]):not([style*="16px"]) > svg > foreignObject:not(:only-child) img {
  -webkit-clip-path: inset(calc(var(--rs-small-spacing) + 1px) calc(var(--rs-small-spacing) + 1px) round var(--rs-avatar-shape));
          clip-path: inset(calc(var(--rs-small-spacing) + 1px) calc(var(--rs-small-spacing) + 1px) round var(--rs-avatar-shape));
}
```
