### ISSUE TITLE
The online display no longer works

### ISSUE THREAD

**Issue by BySwiizen** [DiscordStyles/RadialStatus#79]
### Describe the bug

Since the new update, the display does not work and becomes transparent when the person is connected.

### To Reproduce

Look in the list if someone is online.

### Screenshots

[Screen 1](https://cdn.byswiizen.fr/SCREEN/DiscordCanary_0is7keyRXs.png)
[Screen 2](https://cdn.byswiizen.fr/SCREEN/DiscordCanary_Rfh42g8VML.png)

### Infomation (please complete the following information)

**Discord channel**: Canary
**OS**: Windows  
**Mod**: BetterDiscord
**Discord language**: French

**Comment by Drflash55** [comment]
Due to the newest theme update that Discord pushed out, it breaks RadialStatus completely.

Need to wait until they push out a fix for it.

**Comment by Strana** [comment]
Also occurs on stable

here's my view - mobile indicators still show (may be from my personal modifications to my theme file though)

![Image](https://github.com/user-attachments/assets/0d912206-00df-49a1-8e63-91403f2834e1)

**Comment by FroggMaster** [comment]
This is because the colors have changed and the stroke for the indicator is applied VIA the color's specified fill. 

- The DND Color has changed from: #d83a41 to: #d83a42
- The Idle color has changed from:#cc954c to: #ca9654
- The online color has changed from: #40a258 to: #43a25a

Can be pretty easily fixed if you update the lines:
https://github.com/DiscordStyles/RadialStatus/blob/f36463d7df6d08db97b31a429fa074d1736d94fb/src/main.scss#L84
https://github.com/DiscordStyles/RadialStatus/blob/f36463d7df6d08db97b31a429fa074d1736d94fb/src/main.scss#L88
https://github.com/DiscordStyles/RadialStatus/blob/f36463d7df6d08db97b31a429fa074d1736d94fb/src/main.scss#L92

Personally, I've just captured the CSS from:
https://discordstyles.github.io/RadialStatus/RadialStatus.css

Modified line 70, 73, and 76. 
Appending my modified CSS to the bottom of the theme itself and commenting out: 
@import url('https://discordstyles.github.io/RadialStatus/RadialStatus.css');

**Comment by Drflash55** [comment]
Applying the fixes that FroggMaster stated, you could also throw this into your QuickCSS or theme as well to fix it on your end.
```scss
#app-mount
{
  .wrapper__44b0c
  {
    rect
    {
      &[fill='#23a55a'],
      &[fill='#43a25a']
      {
        stroke: var(--rs-online-color);
      }
      &[fill='#f0b232'],
      &[fill='#ca9654']
      {
        stroke: var(--rs-idle-color);
      }
      &[fill='#f23f43'],
      &[fill='#d83a42']
      {
        stroke: var(--rs-dnd-color);
      }
    }
  }
}
```
